### ISSUE TITLE
Feature Request: Max-AI as the Slack Welcome bot

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/max-ai#4]
### Problem statement

Max-AI has been shipped and available for a few days, but I haven't yet seen much adoption from users. 

Hypothesis is that this is due to a lack of visibility. Users aren't being actively reminded about Max-AI, as it's only really been made visible through tweets and the Changelog process. We don't have a way to constantly tell people: Hey, this is a thing for you to try.

### Proposed solution

We currently have a Zapier-powered welcome bot which gives new users who join the Slack the following message: 

```
Thanks for joining the PostHog community! Here's a quick lowdown:
- *Need help?* Check the community support channel, or <https://posthog.com/questions|ask us a question!> 
- *Just started?* Find tutorials, inspiration and more <https://posthog.com/docs|in our docs>
- *Get involved!* Vote on new features and <https://posthog.com/roadmap|shape our roadmap>!
```

I'm proposing that we remove this welcome bot, and replace it with a message from Max-AI instead. This would cause Max-AI to announce himself to users, and make sure they're aware that it exists, that they can ask it questions. 

I'm not set on wording, but I'd propose something like the following: 

```
Welcome to the PostHog community! I'm Max, the AI hedgehog that's here to help.

If you need **support** then you can ask me anything you want, and I'll do my best to answer. If you'd rather speak to a human,  head to <https://posthog.com/questions|our community support> to ask a question there. You can also ask for support in the app, using the help dropdown. 

Is there anything I can help you with right now?
```

### Alternatives I've considered

We could change the welcome bot to include information if this is too hard to configure, but it's just giving users a more awkward format of the same info.

**Comment by tiina303** [comment]
Could we direct people first to use the help dropdown instead of Squeak, is they are in the app they should use that so we get all the context and there's also a link to squeak there.

**Comment by joethreepwood** [comment]
Yeah, but in order to do that we'd need this to close first: https://github.com/PostHog/posthog/issues/15114

Right now we suggest Squeak because it the only place we can link directly to

**Comment by joethreepwood** [comment]
New suggested copy:

_Welcome to the PostHog community! I'm [Max, the AI hedgehog](https://github.com/PostHog/max-ai) that's here to help._

_**If you need support** then you can ask me anything you want by tagging me. I'll do my best to answer, though I do have a [disclaimer](https://github.com/PostHog/max-ai#disclaimer)._

_If you'd rather speak to a human, you can get support and give feedback in PostHog here(LINK). Requests will automatically be shared with the relevant team._ 

_Is there anything I can help you with right now?_

**Comment by fuziontech** [comment]
Starting to work on this and the only bit that I need some clarification on is:
>If you'd rather speak to a human, you can get support and give feedback in PostHog here(LINK). Requests will automatically be shared with the relevant team.

Where should that be linking to?

**Comment by joethreepwood** [comment]
New process is that it should link to: http://app.posthog.com/home#supportModal

That'll send them to the support modal directly. We didn't have the ability to link directly when I wrote the copy originally.

**Comment by tiina303** [comment]
& you can parametrise the modal too, just use it in the app to see which params you want (after Michael's PR they might be a bit different)
